/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ContentList: typeof import('./src/components/ContentList.vue')['default']
    DataModel: typeof import('./src/components/DataModel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAdd: typeof import('./src/components/UserAdd.vue')['default']
    UserAddPhoto: typeof import('./src/components/UserAddPhoto.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserPhotoManager: typeof import('./src/components/UserPhotoManager.vue')['default']
    UserUpdate: typeof import('./src/components/UserUpdate.vue')['default']
  }
}
