/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUser: typeof import('./src/components/AddUser.vue')['default']
    AddUserPhoto: typeof import('./src/components/AddUserPhoto.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmationBackdrop: typeof import('./src/components/ConfirmationBackdrop.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Inbox: typeof import('./src/components/inbox.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    ListContent: typeof import('./src/components/ListContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    User2: typeof import('./src/components/User2.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
    UserUpdate: typeof import('./src/components/UserUpdate.vue')['default']
  }
}
