/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/content-add-page': RouteRecordInfo<'/content-add-page', '/content-add-page', Record<never, never>, Record<never, never>>,
    '/content-list-page': RouteRecordInfo<'/content-list-page', '/content-list-page', Record<never, never>, Record<never, never>>,
    '/content-update-page': RouteRecordInfo<'/content-update-page', '/content-update-page', Record<never, never>, Record<never, never>>,
    '/data-model-page': RouteRecordInfo<'/data-model-page', '/data-model-page', Record<never, never>, Record<never, never>>,
    '/user-add-page': RouteRecordInfo<'/user-add-page', '/user-add-page', Record<never, never>, Record<never, never>>,
    '/user-add-photo-page': RouteRecordInfo<'/user-add-photo-page', '/user-add-photo-page', Record<never, never>, Record<never, never>>,
    '/user-list-page': RouteRecordInfo<'/user-list-page', '/user-list-page', Record<never, never>, Record<never, never>>,
    '/user-update-page': RouteRecordInfo<'/user-update-page', '/user-update-page', Record<never, never>, Record<never, never>>,
  }
}
